server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false
        write-date-timestamps-as-nanoseconds: false
        read-date-timestamps-as-nanoseconds: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        type:
          json_format_mapper: jackson

logging:
  level:
    com.asc.gymgenie: DEBUG
    org.hibernate.SQL: WARN
    org.springframework.web: INFO

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 15m
    refresh-token-expiration: 30d

gigachat:
  auth-key: ${GIGACHAT_AUTH_KEY}